apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhtap-hub
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-hub 
  name: rhtap-hub
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rhtap-hub 
